# Production overrides for tileserver-rs
# Usage: docker compose -f compose.yml -f compose.prod.yml up -d

services:
  tileserver:
    # Use pre-built image instead of building
    image: ghcr.io/vinayakkulkarni/tileserver-rs:latest

    # Expose on all interfaces
    ports:
      - "${HOST:-0.0.0.0}:${PORT:-8080}:8080"

    # Production volumes (use named volume for tiles)
    volumes:
      - tiles_data:/data:ro
      - ./config.toml:/app/config.toml:ro

    # Production logging level
    environment:
      - RUST_LOG=${RUST_LOG:-info}
      - HOST=0.0.0.0
      - PORT=8080
      - TILESERVER_PUBLIC_URL=${TILESERVER_PUBLIC_URL:-}

    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 256M

volumes:
  tiles_data:
    driver: local
