# Tileserver RS Service
# High-performance vector tile server built in Rust
# Serves PMTiles and MBTiles with MapLibre GL JS visualization

services:
  tileserver:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: tileserver
    restart: unless-stopped
    volumes:
      - app_tiles_volume:/data:ro
      - ../config.toml:/app/config.toml:ro
    environment:
      - RUST_LOG=${RUST_LOG:-info}
      - HOST=0.0.0.0
      - PORT=8080
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
        compress: "true"
